import turtle
bob = turtle.Turtle()
bob.speed(0)

def emoji():
    bob.circle(150)
    bob.penup()
    bob.goto(-60,100)
    bob.pendown()
    bob.forward(130)
    bob.penup()
    bob.goto(-30,150)
    bob.pendown()
    bob.circle(30)
    bob.penup()
    bob.goto(-25,160)
    bob.pendown()
    bob.circle(15)
    bob.penup()
    bob.goto(-27,160)
    bob.pendown()
    bob.circle(10)
    bob.penup()
    bob.goto(30,150)
    bob.pendown()
    bob.circle(30)
